### ISSUE TITLE
llvm-fast flag is not defined in .cabal file!

### ISSUE THREAD

**Issue by juhp** [vmchale/brainheck#1]
You use `llvm-fast` flag in brainheck.cabal but do not define it.
This actually broke stackage-curator!!  Now fixed in git.

(see fpco/stackage#2468)

**Comment by juhp** [comment]
You did the same thing for wordchoice too now :-(

**Comment by vmchale** [comment]
Should be fixed in both `brainheck` and `wordchoice` as of now.

Thanks for the bug report!

**Comment by juhp** [comment]
Thank you!
